### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by dt990pro**

### CODE REVIEW

**Comment by FishPapa** [comment]
look at the code and I just run it. the opponent action bud is fixed and you are good to go.

**Comment by Vacancyy** [comment]
We did the good job. Thanks ALL.

**Comment by huangpujj** [comment]
Does the code fix the problem we faced ?? @dt990pro

**Comment by dt990pro** [comment]
> look at the code and I just run it. the opponent action bud is fixed and you are good to go.

thanks.

I also have it run and it is fixed surely.

**Comment by Vacancyy** [comment]
> > look at the code and I just run it. the opponent action bud is fixed and you are good to go.
> 
> thanks.
> 
> I also have it run and it is fixed surely.

Thanks, dude, you did the good job !

**Comment by dt990pro** [comment]
> Does the code fix the problem we faced ?? @dt990pro

I finished it. Caius made some mistake in other files. And it is good right now. 
the .js file did not deal with char from 'A' to "J'.

**Comment by FishPapa** [comment]
> > Does the code fix the problem we faced ?? @dt990pro
> 
> I finished it. Caius made some mistake in other files. And it is good right now.
> the .js file did not deal with char from 'A' to "J'.

corerct. 
the mistake just gets conflict with if -statement in the board class. and right now it is between 'A' - 'J'
thanks for your efforts.

And your shipplace method is kind too long. it could be abriged since there are lots of if-statements and you could combine some of them.

**Pull request merged**
