### PR TITLE
added board features

### PR DESCRIPTION
**Pull request by dt990pro**
add ship placement and attack features.

### CODE REVIEW

**Comment by FishPapa** [comment]
look at the ship class and it makes sense, the ship is placed at right position.

**Comment by Vacancyy** [comment]
The board features are good and well looking. Nice work.

**Comment by huangpujj** [comment]
I checked your code,  and I think the logic was good to run. However, some functions like placeShip() are so long, that's not good to read. So if you can split the function into different smaller functions, that would help us to read and understand your code and logic..... anyway, nice work!!

**Comment by huangpujj** [comment]
> I checked your code, and I think the logic was good to run. However, some functions like placeShip() are so long, that's not good to read. So if you can split the function into different smaller functions, that would help us to read and understand your code and logic..... anyway, nice work!!
@dt990pro

**Pull request merged**
