### PR TITLE
added five tests file for each class under model packet

### PR DESCRIPTION
**Pull request by huangpujj**

### CODE REVIEW

**Comment by Vacancyy** [comment]
The testing passed all the situations and the converge is over 80% which is good enough for the testing. 
We can still improve more cases to the testing which can get the higher converge.

**Comment by Vacancyy** [comment]
@dt990pro Have you fixed the bugs?

**Comment by Vacancyy** [comment]
@huangpujj Good test!

**Comment by huangpujj** [comment]
> @huangpujj Good test!

Thx, dude

**Comment by huangpujj** [comment]
> @huangpujj Good test!

Thx, dude!

**Comment by dt990pro** [comment]
> @dt990pro Have you fixed the bugs?

I went to meet Caius. 
He said there is a bug that he missed before posting the project.

right now, it work. 
I just played the game.

And yuanjun test it also.

**Comment by dt990pro** [comment]
look at your tests.
it would be better that you can implememnt random test to generate lots of objects to test.
it would cover more cases that you might miss.

**Pull request merged**
